name: Build Rust & Deploy Leptos Page

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      # Build with trunk-rs
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown
          toolchain: nightly-x86_64-unknown-linux-gnu
          components: rust-src
      - name: Install Trunk
        uses: mbround18/trunk-rs@v1
      - name: Build and Deploy Leptos Directory
        run:  trunk build --release
      - name: Print Folder Tree Before Move
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          exclude: ".git|.husky"
          path: ./
          depth: 5
      - name: 'Move files to assets'
        run: mkdir -p dist/assets && cp ./dist/*.js ./dist/assets/ && cp ./dist/*.wasm ./dist/assets/ && cp ./dist/*.css ./dist/assets/

      - name: Fix asset paths in index.html
        run: |
          # Find the JS file name in the assets directory
          JS_FILE=$(find ./dist/assets -type f -name "*.js" -print -quit)
          if [ -n "$JS_FILE" ]; then
          JS_FILENAME=$(basename "$JS_FILE")
          sed -i "s/\/$JS_FILENAME/assets\/$JS_FILENAME/g" ./dist/index.html
          else
          echo "No JS file found in assets!"
          fi

          # Find the WASM file name in the assets directory
          WASM_FILE=$(find ./dist/assets -type f -name "*.wasm" -print -quit)
          if [ -n "$WASM_FILE" ]; then
          WASM_FILENAME=$(basename "$WASM_FILE")
          sed -i "s/\/$WASM_FILENAME/assets\/$WASM_FILENAME/g" ./dist/index.html
          else
          echo "No WASM file found in assets!"
          fi

          # Find the CSS file name in the assets directory
          CSS_FILE=$(find ./dist/assets -type f -name "*.css" -print -quit)
          if [ -n "$CSS_FILE" ]; then
          CSS_FILENAME=$(basename "$CSS_FILE")
          sed -i "s/\/$CSS_FILENAME/assets\/$CSS_FILENAME/g" ./dist/index.html
          else
          echo "No CSS file found in assets!"
          fi

          # Find the favicon.ico file name in the assets directory
          ICO_FILE=$(find ./dist/assets -type f -name "*.ico" -print -quit)
          if [ -n "$ICO_FILE" ]; then
          ICO_FILENAME=$(basename "$ICO_FILE")
          sed -i "s/\/$ICO_FILENAME/assets\/$ICO_FILENAME/g" ./dist/index.html
          else
          echo "No ico file found in assets!"
          fi
      - name: Print Folder Tree After Move
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          exclude: ".git|.husky"
          path: ./
          depth: 5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./dist
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
